name: Check PR

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
    - name: Checkout ac-server-monitor
      uses: actions/checkout@v4
      with:
        repository: 'amoeba/ac-server-monitor'
        path: 'ac-server-monitor'
    - name: Build ac-server-monitor
      working-directory: ./ac-server-monitor
      run: go build
    - name: Extract address and port
      id: extract
      run: |
        echo "CHECK_ADDRESS=play.coldeve.online" >> "$GITHUB_OUTPUT"
        echo "CHECK_PORT=9000" >> "$GITHUB_OUTPUT"
    - name: Check server
      env:
        CHECK_ADDRESS: ${{ steps.extract.outputs.CHECK_ADDRESS }}
        CHECK_PORT: ${{ steps.extract.outputs.CHECK_PORT }}
      working-directory: ./ac-server-monitor
      run: ./monitor -check $ADDRESS:$PORT
